# Generated by Django 3.1.1 on 2020-09-09 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=99)),
                ('char_class', models.CharField(choices=[('JUIC', 'Juicer'), ('SYMB', 'Symbient'), ('MACH', 'Machinist'), ('CIPH', 'Cipher')], max_length=4)),
                ('char_race', models.CharField(choices=[('O_DU', 'Old Worlder, Stardust'), ('O_BL', 'Old Worlder, Black'), ('O_WH', 'Old Worlder, White'), ('O_NE', 'Old Worlder, Nebula'), ('P_DR', 'Peasant, Dreamer'), ('P_AR', 'Peasant, Arsons'), ('T_TU', 'Tecchi, Turing'), ('T_NI', 'Tecchi, Nikola'), ('T_EN', 'Tecchi, Ender'), ('N_MA', 'Noble, Mars'), ('N_AL', 'Noble, Alsaud'), ('N_BO', 'Noble, Boehringer'), ('N_DU', 'Noble, Dumas'), ('P_EC', 'Patrician, Ecstasy'), ('P_DR', 'Patrician, Drunkard'), ('P_EX', 'Patrician, Expanded')], max_length=4)),
                ('str', models.IntegerField()),
                ('dex', models.IntegerField()),
                ('con', models.IntegerField()),
                ('wis', models.IntegerField()),
                ('int', models.IntegerField()),
                ('end', models.IntegerField()),
                ('user_rec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
